export const clerkAppearance = {
  variables: {
    colorPrimary: "#20E7D5",
    colorText: "#F4F8FB",
    colorTextSecondary: "#8EA3B3",
    colorBackground: "transparent",
    colorInputBackground: "#0E151D",
    colorInputText: "#F4F8FB",
    colorDanger: "#FF7D7D",
    borderRadius: "1rem",
    fontFamily: "var(--font-sans)",
  },
  elements: {
    rootBox: "w-full",
    cardBox: "w-full shadow-none",
    card: "w-full rounded-[var(--ui-radius-panel)] border border-border/80 bg-card p-2 shadow-none sm:p-3",
    headerTitle: "font-heading text-[1.7rem] tracking-tight text-foreground",
    headerSubtitle: "mt-2 text-sm leading-7 text-muted-foreground",
    socialButtonsBlockButton:
      "h-12 rounded-2xl border border-border bg-card shadow-none transition-colors hover:bg-secondary/55",
    socialButtonsBlockButtonText: "text-sm font-medium text-foreground",
    dividerLine: "bg-border",
    dividerText:
      "text-[0.7rem] font-semibold uppercase tracking-[0.14em] text-muted-foreground",
    formFieldLabel:
      "text-[0.7rem] font-semibold uppercase tracking-[0.14em] text-muted-foreground",
    formFieldInput:
      "h-12 rounded-2xl border border-input bg-muted px-4 text-sm text-foreground shadow-none transition-[border-color,box-shadow] focus:border-primary/55 focus:ring-4 focus:ring-ring",
    formFieldInputShowPasswordButton: "text-muted-foreground hover:text-foreground",
    formFieldAction: "text-sm font-medium text-muted-foreground hover:text-foreground",
    formButtonPrimary:
      "h-11 rounded-full bg-primary text-primary-foreground shadow-none transition-colors hover:bg-primary/95",
    footerActionText: "text-sm text-muted-foreground",
    footerActionLink: "font-medium text-foreground hover:text-primary",
    footerPages: "hidden",
    footerPageLink: "hidden",
    formResendCodeLink: "font-medium text-foreground hover:text-primary",
    identityPreviewText: "text-sm text-foreground",
    identityPreviewEditButton: "font-medium text-foreground hover:text-primary",
    alert:
      "rounded-2xl border border-border/80 bg-secondary/55 text-sm text-foreground shadow-none",
    alertText: "text-sm leading-6 text-foreground",
    otpCodeFieldInput:
      "h-12 rounded-2xl border border-input bg-card text-sm text-foreground shadow-none",
    userButtonPopoverCard:
      "overflow-hidden rounded-[var(--ui-radius-panel)] border border-border/80 bg-card text-foreground shadow-2xl shadow-black/40",
    userButtonPopoverMain: "bg-card",
    userButtonPopoverFooter: "bg-secondary/60",
    userButtonPopoverActionButton:
      "text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground",
    userButtonPopoverActionButtonText: "text-sm font-medium",
    userButtonPopoverActionButtonIcon: "text-muted-foreground",
    userPreviewMainIdentifier: "font-semibold text-foreground",
    userPreviewSecondaryIdentifier: "text-muted-foreground",
    userProfileRoot: "w-full",
    userProfileCard:
      "rounded-[var(--ui-radius-panel)] border border-border/80 bg-card text-foreground shadow-2xl shadow-black/40",
    userProfileNavbar:
      "border-r border-border/80 bg-secondary/45 text-foreground",
    userProfileNavbarButton:
      "text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground",
    userProfileNavbarButtonActive: "bg-secondary text-foreground",
    userProfilePageScrollBox: "bg-card",
    userProfileSectionTitle: "font-heading text-foreground",
    userProfileSectionContent: "text-foreground",
    profileSectionPrimaryButton:
      "rounded-full bg-primary text-primary-foreground hover:bg-primary/90",
  },
} as const;

export const clerkLocalization = {
  locale: "ro-RO",
  socialButtonsBlockButton: "Continuă cu {{provider|titleize}}",
  socialButtonsBlockButtonManyInView: "{{provider|titleize}}",
  dividerText: "sau",
  lastAuthenticationStrategy: "Folosit recent",
  formFieldLabel__emailAddress: "Adresă de email",
  formFieldLabel__emailAddresses: "Adrese de email",
  formFieldLabel__password: "Parolă",
  formFieldLabel__currentPassword: "Parola curentă",
  formFieldLabel__newPassword: "Parolă nouă",
  formFieldLabel__confirmPassword: "Confirmă parola",
  formFieldLabel__firstName: "Prenume",
  formFieldLabel__lastName: "Nume",
  formFieldInputPlaceholder__emailAddress: "Introdu adresa de email",
  formFieldInputPlaceholder__password: "Introdu parola",
  formFieldInputPlaceholder__signUpPassword: "Creează o parolă",
  formFieldInputPlaceholder__firstName: "Introdu prenumele",
  formFieldInputPlaceholder__lastName: "Introdu numele",
  formFieldError__notMatchingPasswords: "Parolele nu coincid.",
  formButtonPrimary: "Continuă",
  formButtonPrimary__verify: "Verifică",
  formButtonPrimary__continue: "Continuă",
  badge__primary: "Principală",
  badge__thisDevice: "Acest dispozitiv",
  badge__unverified: "Neverificat",
  footerActionLink__useAnotherMethod: "Folosește altă metodă",
  backButton: "Înapoi",
  signIn: {
    start: {
      title: "Autentificare",
      titleCombined: "Autentificare",
      subtitle: "Intră în cont pentru a gestiona livrările SkySend.",
      subtitleCombined: "Intră în cont pentru a continua.",
      actionText: "Nu ai cont?",
      actionLink: "Creează cont",
    },
    password: {
      title: "Introdu parola",
      subtitle: "Continuă autentificarea în SkySend.",
      actionLink: "Folosește altă metodă",
    },
    forgotPassword: {
      title: "Resetează parola",
      subtitle: "Primești un cod de verificare pentru a seta o parolă nouă.",
      subtitle_email: "Primești un cod la adresa de email.",
      formTitle: "Cod de verificare",
      resendButton: "Retrimite codul",
    },
    resetPassword: {
      title: "Setează parola nouă",
      formButtonPrimary: "Salvează parola",
      successMessage: "Parola a fost actualizată.",
      requiredMessage: "Introdu o parolă nouă.",
    },
    emailCode: {
      title: "Verifică emailul",
      subtitle: "Introdu codul primit pe email.",
      formTitle: "Cod de verificare",
      resendButton: "Retrimite codul",
    },
  },
  signUp: {
    start: {
      title: "Creează contul",
      titleCombined: "Creează contul",
      subtitle: "Completează datele pentru a începe.",
      subtitleCombined: "Completează datele pentru a începe.",
      actionText: "Ai deja cont?",
      actionLink: "Autentifică-te",
    },
    emailCode: {
      title: "Verifică emailul",
      subtitle: "Introdu codul primit pe email pentru a finaliza contul.",
      formTitle: "Cod de verificare",
      formSubtitle: "Codul a fost trimis la adresa ta de email.",
      resendButton: "Retrimite codul",
    },
    continue: {
      title: "Finalizează contul",
      subtitle: "Mai avem nevoie de câteva detalii pentru cont.",
      actionText: "Ai deja cont?",
      actionLink: "Autentifică-te",
    },
  },
  userButton: {
    action__manageAccount: "Gestionează contul",
    action__signOut: "Deconectare",
    action__signOutAll: "Deconectare din toate sesiunile",
    action__addAccount: "Adaugă cont",
    action__openUserMenu: "Deschide meniul contului",
    action__closeUserMenu: "Închide meniul contului",
  },
  userProfile: {
    formButtonPrimary__continue: "Continuă",
    formButtonPrimary__save: "Salvează",
    formButtonPrimary__finish: "Finalizează",
    formButtonPrimary__remove: "Elimină",
    formButtonPrimary__add: "Adaugă",
    formButtonReset: "Anulează",
    navbar: {
      title: "Cont",
      description: "Gestionează informațiile contului.",
      account: "Cont",
      security: "Securitate",
      billing: "Plăți",
      apiKeys: "Chei API",
    },
    start: {
      headerTitle__account: "Cont",
      headerTitle__security: "Securitate",
      profileSection: {
        title: "Profil",
        primaryButton: "Actualizează profilul",
      },
      emailAddressesSection: {
        title: "Adrese de email",
        primaryButton: "Adaugă adresă de email",
        detailsAction__primary: "Principală",
        detailsAction__nonPrimary: "Setează ca principală",
        detailsAction__unverified: "Verifică adresa",
        destructiveAction: "Elimină adresa",
      },
      connectedAccountsSection: {
        title: "Conturi conectate",
        primaryButton: "Conectează cont",
        actionLabel__connectionFailed: "Conexiunea a eșuat",
        actionLabel__reauthorize: "Reconectează",
        subtitle__disconnected: "Cont deconectat",
        subtitle__reauthorize: "Reconectarea este necesară",
        destructiveActionTitle: "Elimină contul conectat",
      },
      passwordSection: {
        title: "Parolă",
        primaryButton__updatePassword: "Actualizează parola",
        primaryButton__setPassword: "Setează parola",
      },
    },
  },
} as const;
