import type { DroneConfig } from "@/types/drone";

export const droneFleet: readonly DroneConfig[] = [
  {
    id: "light_swift",
    name: "Light Swift",
    imageSrc: "/drones/light-swift.png",
    category: "light",
    shortDescription: "Fast and efficient drone for compact parcels and urgent city routes.",
    maxPayloadKg: 1.2,
    maxVolumeLiters: 4,
    maxDimensionsCm: { lengthCm: 22, widthCm: 18, heightCm: 10 },
    maxParcelDimensionsCm: { lengthCm: 22, widthCm: 18, heightCm: 10 },
    averageSpeedKmh: 72,
    estimatedSpeedKph: 72,
    rangeKm: 12,
    estimatedRangeKm: 12,
    lockerSize: "compact",
    baseMultiplier: 0.92,
    perKmMultiplier: 0.94,
    dispatchMultiplier: 0.96,
    strengths: ["Fast dispatch", "Lower fare", "Compact route profile"],
    limitations: ["Small locker", "Not ideal for fragile goods"],
    bestFor: ["Documents", "Small retail", "Urgent compact parcels"],
    suitabilityTags: ["dense_urban", "high_priority", "same_hour"],
    recommendedUseCases: ["Documents", "Small retail", "Urgent compact parcels"],
  },
  {
    id: "light_secure",
    name: "Light Secure",
    imageSrc: "/drones/light-secure.png",
    category: "light",
    shortDescription: "Compact drone with reinforced locker handling for sensitive small parcels.",
    maxPayloadKg: 1.6,
    maxVolumeLiters: 5,
    maxDimensionsCm: { lengthCm: 24, widthCm: 20, heightCm: 12 },
    maxParcelDimensionsCm: { lengthCm: 24, widthCm: 20, heightCm: 12 },
    averageSpeedKmh: 60,
    estimatedSpeedKph: 60,
    rangeKm: 14,
    estimatedRangeKm: 14,
    lockerSize: "secure_compact",
    baseMultiplier: 1.02,
    perKmMultiplier: 1,
    dispatchMultiplier: 1.02,
    strengths: ["Secure locker", "Careful handling", "Good for small fragile items"],
    limitations: ["Limited payload", "Moderate speed"],
    bestFor: ["Small electronics", "Pharmacy packs", "Sensitive documents"],
    suitabilityTags: ["dense_urban", "fragile_goods", "medical", "same_hour"],
    recommendedUseCases: ["Small electronics", "Pharmacy packs", "Sensitive documents"],
  },
  {
    id: "medium_standard",
    name: "Medium Standard",
    imageSrc: "/drones/medium-standard.png",
    category: "medium",
    shortDescription: "Balanced default drone for most same-hour deliveries in Pitesti.",
    maxPayloadKg: 3,
    maxVolumeLiters: 14,
    maxDimensionsCm: { lengthCm: 35, widthCm: 28, heightCm: 18 },
    maxParcelDimensionsCm: { lengthCm: 35, widthCm: 28, heightCm: 18 },
    averageSpeedKmh: 58,
    estimatedSpeedKph: 58,
    rangeKm: 20,
    estimatedRangeKm: 20,
    lockerSize: "standard",
    baseMultiplier: 1,
    perKmMultiplier: 1,
    dispatchMultiplier: 1,
    strengths: ["Balanced fare", "Good payload", "Reliable urban range"],
    limitations: ["Not specialized for heavy cargo", "Moderate fragile support"],
    bestFor: ["Food orders", "Retail parcels", "Routine business handoffs"],
    suitabilityTags: ["dense_urban", "same_hour", "weather_resilient"],
    recommendedUseCases: ["Food orders", "Retail parcels", "Routine business handoffs"],
  },
  {
    id: "medium_stabilized",
    name: "Medium Stabilized",
    imageSrc: "/drones/medium-stabilized.png",
    category: "medium",
    shortDescription: "Stabilized flight and locker profile for fragile or sensitive payloads.",
    maxPayloadKg: 2.8,
    maxVolumeLiters: 12,
    maxDimensionsCm: { lengthCm: 32, widthCm: 26, heightCm: 17 },
    maxParcelDimensionsCm: { lengthCm: 32, widthCm: 26, heightCm: 17 },
    averageSpeedKmh: 48,
    estimatedSpeedKph: 48,
    rangeKm: 18,
    estimatedRangeKm: 18,
    lockerSize: "stabilized",
    baseMultiplier: 1.14,
    perKmMultiplier: 1.08,
    dispatchMultiplier: 1.06,
    strengths: ["Stabilized handling", "Fragile support", "Controlled locker movement"],
    limitations: ["Higher fare", "Lower average speed"],
    bestFor: ["Fragile items", "Medical packs", "Delicate electronics"],
    suitabilityTags: ["fragile_goods", "medical", "high_priority"],
    recommendedUseCases: ["Fragile items", "Medical packs", "Delicate electronics"],
  },
  {
    id: "medium_long_range",
    name: "Medium Long Range",
    imageSrc: "/drones/medium-long-range.png",
    category: "medium",
    shortDescription: "Extended autonomy drone for longer routes across the active city zone.",
    maxPayloadKg: 2.5,
    maxVolumeLiters: 11,
    maxDimensionsCm: { lengthCm: 34, widthCm: 25, heightCm: 16 },
    maxParcelDimensionsCm: { lengthCm: 34, widthCm: 25, heightCm: 16 },
    averageSpeedKmh: 54,
    estimatedSpeedKph: 54,
    rangeKm: 38,
    estimatedRangeKm: 38,
    lockerSize: "standard",
    baseMultiplier: 1.12,
    perKmMultiplier: 1.14,
    dispatchMultiplier: 1.05,
    strengths: ["Longer autonomy", "Good range reserve", "Stable cross-city routing"],
    limitations: ["Higher distance cost", "Not for heavy parcels"],
    bestFor: ["Longer city routes", "Cross-district deliveries", "Priority range reserve"],
    suitabilityTags: ["long_distance", "weather_resilient", "same_hour"],
    recommendedUseCases: ["Longer city routes", "Cross-district deliveries", "Priority range reserve"],
  },
  {
    id: "heavy_cargo",
    name: "Heavy Cargo",
    imageSrc: "/drones/heavy-cargo.png",
    category: "heavy",
    shortDescription: "High-capacity drone for larger parcels and consolidated logistics runs.",
    maxPayloadKg: 8,
    maxVolumeLiters: 55,
    maxDimensionsCm: { lengthCm: 55, widthCm: 42, heightCm: 30 },
    maxParcelDimensionsCm: { lengthCm: 55, widthCm: 42, heightCm: 30 },
    averageSpeedKmh: 40,
    estimatedSpeedKph: 40,
    rangeKm: 24,
    estimatedRangeKm: 24,
    lockerSize: "large",
    baseMultiplier: 1.26,
    perKmMultiplier: 1.18,
    dispatchMultiplier: 1.12,
    strengths: ["Large payload", "Large locker", "Strong stability"],
    limitations: ["Slower route speed", "Higher fare"],
    bestFor: ["Bulk retail", "Large grocery packs", "Business supplies"],
    suitabilityTags: ["heavy_payload", "weather_resilient", "long_distance"],
    recommendedUseCases: ["Bulk retail", "Large grocery packs", "Business supplies"],
  },
  {
    id: "heavy_max",
    name: "Heavy Max",
    imageSrc: "/drones/heavy-max.png",
    category: "heavy",
    shortDescription: "Largest SkySend drone for oversized eligible parcels and maximum locker volume.",
    maxPayloadKg: 12,
    maxVolumeLiters: 85,
    maxDimensionsCm: { lengthCm: 70, widthCm: 50, heightCm: 36 },
    maxParcelDimensionsCm: { lengthCm: 70, widthCm: 50, heightCm: 36 },
    averageSpeedKmh: 34,
    estimatedSpeedKph: 34,
    rangeKm: 18,
    estimatedRangeKm: 18,
    lockerSize: "max",
    baseMultiplier: 1.48,
    perKmMultiplier: 1.32,
    dispatchMultiplier: 1.2,
    strengths: ["Maximum payload", "Maximum locker volume", "Best oversized fit"],
    limitations: ["Highest fare", "Shorter range", "Slowest model"],
    bestFor: ["Oversized parcels", "Dense heavy loads", "Special cargo"],
    suitabilityTags: ["heavy_payload", "weather_resilient"],
    recommendedUseCases: ["Oversized parcels", "Dense heavy loads", "Special cargo"],
  },
] as const;

export const droneFleetById = Object.fromEntries(
  droneFleet.map((drone) => [drone.id, drone]),
) as Record<(typeof droneFleet)[number]["id"], (typeof droneFleet)[number]>;

export const legacyDroneClassMap = {
  light_express: "light_swift",
  standard_courier: "medium_standard",
  fragile_care: "medium_stabilized",
  long_range: "medium_long_range",
  heavy_cargo: "heavy_cargo",
} as const;
